#!/bin/bash
# Krita : https://download.kde.org/stable/krita/3.3.0/krita-3.3.0-x86_64.appimage
# Télécharge et installe HornetQ dans /opt
KRITA_VERSION="3.3.1"
BASE_URL_KRITA="https://download.kde.org/stable/krita/${KRITA_VERSION}"
PACKAGE_FILENAME_KRITA="krita-${KRITA_VERSION}-x86_64.appimage"
#PACKAGE_NAME_KRITA=$(basename -s .tar.bz2 $PACKAGE_FILENAME_KRITA)
PACKAGE_NAME_KRITA=$PACKAGE_FILENAME_KRITA

PATH_TARGET="/opt/krita"
PATH_CURRENT="$PATH_TARGET/krita-current"

# Prépare l'arborescence maître
if [ ! -d "$PATH_TARGET" ]; then
  mkdir -p $PATH_TARGET
  RESULT=$?
  if [ ! $RESULT -eq 0 ]; then
    exit $RESULT
  fi
fi

# Télécharge
cd $PATH_TARGET
if [ ! -f "$PACKAGE_FILENAME_KRITA" ]; then
  wget --header="Accept: text/html" --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0" -O $PACKAGE_FILENAME_KRITA $BASE_URL_KRITA/$PACKAGE_FILENAME_KRITA
  RESULT=$?
  if [ ! $RESULT -eq 0 ]; then
    exit $RESULT
  fi
  chmod 755 $PACKAGE_FILENAME_KRITA
fi

# Décompresse
#tar -xjf $PACKAGE_FILENAME_KRITA
#RESULT=$?
#if [ ! $RESULT -eq 0 ]; then
#  exit $RESULT
#fi

# Crée le lien pour la version courante.
if [ -f "$PATH_CURRENT" ]; then
  rm $PATH_CURRENT
  RESULT=$?
  if [ ! $RESULT -eq 0 ]; then
    exit $RESULT
  fi
fi

ln -s $PACKAGE_NAME_KRITA $PATH_CURRENT
RESULT=$?
if [ ! $RESULT -eq 0 ]; then
  exit $RESULT
fi
